"""add status to story

Revision ID: 6c7614bfcaca
Revises: a64f13d27569
Create Date: 2020-03-05 22:48:34.618667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7614bfcaca'
down_revision = 'a64f13d27569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'status')
    # ### end Alembic commands ###
